meeting_action_plan/action_plan/urls.py
from django.conf.urls import patterns,url
from django.contrib.auth.decorators import login_required
from action_plan.views import*
urlpatterns = patterns('',
	url(r'login/$',  Login.as_view(), name='login'),
    url(r'logout/$', Logout.as_view(), name='logout'),
    url(r'^$', login_required(Home.as_view()), name='home'),
    url(r'add_department/$',  login_required(AddDepartmentView.as_view()), name='add_department'),
    url(r'departments/$',login_required(DepartmentView.as_view()),name='departments'),
    url(r'users/$',login_required (UserView.as_view()),name='users'),
    url(r'actionplans/$',login_required(ActionPlanView.as_view()),name='actionplans'),
    url(r'add_user/$',login_required(AddUserView.as_view()), name='add_user'),
    
    url(r'add_actionplan/$',login_required(AddActionPlanView.as_view()), name='add_actionplan'),
    url(r'deletedepartment/(?P<department_id>\d+)/$',login_required(DeleteDepartment.as_view()), name='deletedepartment'),
    url(r'deleteuser/(?P<user_id>\d+)/$',login_required(DeleteUser.as_view()), name='deleteuser'),
    url(r'delete_action_plan/(?P<actionplan_id>\d+)/$',login_required(DeleteActionPlan.as_view()), name='delete_action_plan'),
   	url(r'editdepartment/(?P<department_id>\d+)/$', login_required(EditDepartment.as_view()), name='editdepartment'),
   	url(r'edituser/(?P<user_id>\d+)/$',login_required(EditUser.as_view()), name='edituser'),
    url(r'editactionplan/(?P<actionplan_id>\d+)/$',login_required(EditActionPlan.as_view()), name='editactionplan'),
    )

meeting_action_plan/meeting_action_plan/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'meeting_action_plan.views.home', name='home'),
    # url(r'^meeting_action_plan/', include('meeting_action_plan.foo.urls')),
	url(r'^',include('action_plan.urls') ),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

)

meeting_action_plan/action_plan/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

PRIORITY_CHOICES  =(
            ('1','one'),
            ('2','two'),
            ('3','three'),
    )
STATUS_CHOICES =(
            ('Open','Open'),
            ('Closed','Closed'),
    )
class Department(models.Model):

    name = models.CharField('Department Name', max_length=200, unique=True)
    head = models.ForeignKey(User, null=True, blank=True)
    def __unicode__(self):
        return self.name


class ActionPlan(models.Model):

    date_opened = models.DateTimeField('Date Opened',null=True,blank=True)
    action = models.TextField('Requirement/Action', null=True, blank=True)
    focal = models.CharField('Task Assigned To', max_length=200, null=True, blank=True)
    priority = models.CharField( max_length=1, choices=PRIORITY_CHOICES)
    status = models.CharField( max_length=10, choices=STATUS_CHOICES)
    date_closed = models.DateTimeField('Date Closed', null=True, blank=True)
    target_date = models.DateTimeField('Target Date', null=True, blank=True)
    comments = models.TextField('Comments/Update', null=True, blank=True)
    department = models.ForeignKey(Department, null=True, blank=True)

    def __unicode__(self):
        return self.department.name 

meeting_action_plan/action_plan/forms.py
from action_plan.models import *
from django.forms import ModelForm
from django import forms

class DepartmentForm(ModelForm):
	class Meta:

		model = Department
		fields = ['name','head']

# class DepartmentHeadForm(ModelForm):
# 	class Meta:

# 		model = DepartmentHead
# 		fields = ['department', 'user']

class ActionPlanForm(ModelForm):
	class Meta:

		model = ActionPlan
		exclude = ['department']
		fields = ['action', 'focal', 'status', 'comments']

meeting_action_plan/action_plan/views.py
from action_plan.models import*
import datetime as dt
from datetime import datetime
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.base import View
from django.shortcuts import  render
from django.views.generic.base import View
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from action_plan.forms import DepartmentForm,ActionPlanForm
from django.db import IntegrityError
from django.db import transaction, DatabaseError

class Home(View):
    def get(self,request):
        return render(request, 'home.html', {})


class Login(View):
    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('home'))
        return render(request,'login.html',{})

    def post(self,request,*args,**kwargs):
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user and user.is_active:
            login(request, user)
        else:
            context = {
                'message' : 'Username or password is incorrect'
            }
            return render(request, 'login.html',context)
        context = {
         'Success_message': 'Welcome '+request.POST['username']
        }
        return HttpResponseRedirect(reverse('actionplans'))

class Logout(View):
    def get(self,request,*args,**kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('login'))

class DepartmentView(generic.ListView):
    template_name = 'department.html'
    context_object_name = 'latest_department_list'
    def get_queryset(self):
        department = Department.objects.order_by('name')
        return department

class UserView(generic.ListView):
    template_name = 'users.html'
    context_object_name = 'latest_user_list'
    def get_queryset(self):
        users = User.objects.order_by('username').exclude(is_superuser=True)
        return users

class ActionPlanView(View):
    def get(self, request, *args, **kwargs):
        actionplans_opened= ActionPlan.objects.filter(status='Open').order_by('target_date')
        actionplans_closed= ActionPlan.objects.filter(status='Closed').order_by('-date_closed')
        context = { 
            'actionplans_opened':actionplans_opened,
            'actionplans_closed':actionplans_closed,
        }
        return render(request,'actionplan.html',context)

class AddDepartmentView(View):
    def get(self, request, *args, **kwargs):
        users = User.objects.all()
        return render(request, 'add_department.html', {'users': users})
    def post(self, request, *args, **kwargs):
        users = User.objects.all()
        try:
            department = Department.objects.get(name=request.POST['name'])
            
            context = {'users': users, 'message': 'Department name already exists'}
            context.update(request.POST)
            return render(request, 'add_department.html', context)
        except:
            
            user_id=request.POST['user_id']
            if request.POST['name'] !='' and request.POST['name'] !=None and len(request.POST['name']) > 0:
                department = Department() 
                department.name = request.POST['name']
                if user_id != 'None': 
                    user = User.objects.get(id=user_id)       
                    department.head = user
                department.save()
            else:
                return render(request, 'add_department.html', {'message':'Department name is null','users': users, })
        return HttpResponseRedirect(reverse('departments'))

class AddUserView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'add_user.html',{})
    def post(self, request, *args, **kwargs):
        try:
            user = User.objects.get(username=request.POST['username'])
            context = {
                'message': 'Sorry..This username already exists'
            }
            return render(request, 'add_user.html',context)
        except:
            user = User()
            if request.POST['username'] !='':
                user.username = request.POST['username']
                user.first_name = User(request.POST['firstname'])
                user.last_name = User(request.POST['lastname'])
                user.save()
                user.set_password(request.POST['password'])
                user.save()    
                return HttpResponseRedirect(reverse('users'))
            else:
                return render(request, 'add_user.html',{'message':'Username is blank'})

class AddActionPlanView(View):
    def get(self,request,*args,**kwargs):
        departments = Department.objects.all()
        plan = ActionPlan.objects.all()
        if request.method == 'GET':
            
            formplan = ActionPlanForm()
            context ={
                'plan':plan,
                'departments':departments,
                'formplan':formplan,
            }
            return render(request, 'add_actionplan.html', context)

    def post(self,request,*args,**kwargs):
        if request.method == 'POST':
            form = ActionPlanForm(request.POST)
            departments = Department.objects.all()
            plan = ActionPlan.objects.all()
            
            if form.is_valid():
                form.save()
                target_date = datetime.strptime(request.POST['target_date'], '%d/%m/%Y')
                
                current_time = datetime.now().time()
                target_date = target_date.replace(hour=current_time.hour, minute=current_time.minute)
                if request.user.is_superuser:
                    department_id = request.POST['department_id']
                    department = Department.objects.get(id=department_id)
                    plan = ActionPlan.objects.latest('id')
                    plan.department = department
                    plan.save()
                else:
                    department_name = request.POST['department_name']
                    department = Department.objects.get(name=department_name)
                    plan = ActionPlan.objects.latest('id')
                    plan.department =department
                    plan.save()
                if plan.status == 'Open':
                    plan.date_opened = datetime.now()
                else:
                    plan.date_closed = datetime.now()
                plan.target_date = target_date
                plan.save()

                return HttpResponseRedirect(reverse('actionplans'))
            
            context ={
                'plan':plan,
                'departments':departments,
                'formplan':form,
            }
            return render(request, 'add_actionplan.html', context)
class DeleteDepartment(View):
    def get(self,request,*args,**kwargs):
        department_id = kwargs['department_id']
        department = Department.objects.get(id=department_id)
        department.delete()
        return HttpResponseRedirect(reverse('departments'))

class DeleteUser(View):
    def get(self,request,*args,**kwargs):

        user_id = kwargs['user_id']
        user = User.objects.get(id=user_id)
        user.delete()
        return HttpResponseRedirect(reverse('users'))

class DeleteActionPlan(View):
    def get(self,request,*args,**kwargs):

        if request.user.is_superuser:
            actionplan_id = kwargs['actionplan_id']
            actionplan = ActionPlan.objects.get(id=actionplan_id)
            actionplan.delete()
        return HttpResponseRedirect(reverse('actionplans'))

class EditDepartment(View):

    def get(self,request,*args,**kwargs):
        
        department_id = kwargs['department_id']
        department = Department.objects.get(id=department_id)
        users = User.objects.all()
        if request.method == 'GET':
            context = {
                'users':users,
                'department':department,
                'department_id':department_id,
            }
            return render(request,'edit_department.html',context)

    def post(self,request,*args,**kwargs):

        department_id = kwargs['department_id']
        department = Department.objects.get(id=department_id)
        user_id=request.POST['user_id']
        users = User.objects.all()
        if request.method == 'POST': 
            try:  
                department.name = request.POST['name']
                department.save()
                if request.POST['name'] !='':
                    if user_id != 'None':
                        head = User.objects.get(id=user_id)       
                        department.head = head
                    department.save()
                    return HttpResponseRedirect(reverse('departments'))
                else :
                    return render(request, 'edit_department.html',{'department_id':department_id,'department':department,'users':users,'message':'Department name is blank'})
            except DatabaseError:
                try:
                    transaction.rollback()
                except transaction.TransactionManagementError:
                    users = User.objects.all()
            context = {'users' : users,'department_id':department_id, 'department':department, 'message':'Department name ' + request.POST['name']+ ' already exists'}
            return render(request ,'edit_department.html',context)

        

class EditUser(View):

    def get(self,request,*args,**kwargs):
        user_id = kwargs['user_id']
        users = User.objects.get(id=user_id)
        if request.method == 'GET':
            context = {
                'users':users,
                'user_id':user_id,
            }
            return render(request,'edit_user.html',context)
    def post(self, request, *args, **kwargs):
        user_id = kwargs['user_id']

meeting_action_plan/action_plan/templates/actionplan.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-info" align="Center"><h4>Action Plans</h4></div>
<div class="actidafon">
	{% if actionplans_opened or actionplans_closed %}
		<div class="table_container">
			<div class="table_header">
				<div class="th1">Date Opened</div>
				<div class="th2">Requirement/Action</div>
				<div class="th3">Task Assigned To</div>
				<div class="th4">Status</div>
				<div class="th5">Target Date</div>
				<div class="th6">Date Closed</div>
				<div class="th7">Comments/Update</div>
				<div class="th8">Owner</div>
				<div class="th9"></div>
				<div class="th10"></div>				
			</div>
			{% for actionplan in actionplans_opened %}
				<div class="table_row">
					<div class="th1 td">{{actionplan.date_opened|date:'d/m/y'}}</div>
					<div class="th2 td">{{actionplan.action}}</div>
					<div class="th3 td">{{actionplan.focal}}</div>
					
					{% if actionplan.status == 'Open' %}
						<div class="red th4 td">
					{% elif actionplan.status == 'Closed' %}
						<div class="green th4 td">
					{% else %}
						<div class="th4 td"> 
					{% endif %}
						{{actionplan.status}}</div>
					<div class="th5 td">{{actionplan.target_date|date:'d/m/y'}}</div>
					<div class="th6 td">{{actionplan.date_closed|date:'d/m/y'}}</div>
					<div class="th7 td">{{actionplan.comments}}</div>
					<div class="th8 td">{{actionplan.department.name}}</div>
					{% if user.is_superuser %}
						<div class="th9 td"><a href="{% url 'editactionplan' actionplan.id %}">Edit</a></div>
						<div class="th10 td"><a href="{% url 'delete_action_plan' actionplan.id %}">Delete</a></div>
					{% endif %}
					<div class="clear"></div>
				</div>
			{% endfor %}
			{% for actionplan in actionplans_closed %}
				<div class="table_row">
					<div class="th1 td">{{actionplan.date_opened|date:'d/m/y'}}</div>
					<div class="th2 td">{{actionplan.action}}</div>
					<div class="th3 td">{{actionplan.focal}}</div>
					
					{% if actionplan.status == 'Open' %}
						<div class="red th4 td">
					{% elif actionplan.status == 'Closed' %}
						<div class="green th4 td">
					{% else %}
						<div class="th4 td"> 
					{% endif %}
						{{actionplan.status}}</div>
					<div class="th5 td">{{actionplan.target_date|date:'d/m/y'}}</div>
					<div class="th6 td">{{actionplan.date_closed|date:'d/m/y'}}</div>
					<div class="th7 td">{{actionplan.comments}}</div>
					<div class="th8 td">{{actionplan.department.name}}</div>
					{% if user.is_superuser %}
						<div class="th9 td"><a href="{% url 'editactionplan' actionplan.id %}">Edit</a></div>
						<div class="th10 td"><a href="{% url 'delete_action_plan' actionplan.id %}">Delete</a></div>
					{% endif %}
					<div class="clear"></div>
				</div>
			{% endfor %}
		</div>	
	{% else %}		
	    <p>No Action Plans are available.</p>
	{% endif %}
	<div class ="plan_button">
		<a href="{% url 'add_actionplan' %}">
	        <input type='submit' value='Add a new action plan'/>
	    </a>
	</div>
</div>
{% endblock content %}

meeting_action_plan/action_plan/templates/add_actionplan.html
{% extends 'base.html' %}
{% block extraheader %}
	<script> 
		$( document ).ready(function() {
			new Picker.Date($$('#target_date'), {
	            timePicker: false,
	            positionOffset: {x: 5, y: 0},
	            pickerClass: 'datepicker_bootstrap',
	            useFadeInOut: !Browser.ie,
	            format:'%d/%m/%Y',
	        });
		});
		
	</script>
	
{% endblock extraheader %}
{% block content %}

<div class="alert alert-info" align="Center"><h4>Add Action Plan</h4></div>

<div class="add_plan">
	<form method="post" action="{% url 'add_actionplan' %}">{% csrf_token %}
		{% for field in formplan.visible_fields %}

			<label> {{field.label}}</label>
				{{field}}
				{{field.errors}}
		{% endfor %}
		<label> Target Date</label>
		<input id="target_date" type="text" name="target_date">
		<label>Department Name:</label>
		{%if user.is_superuser%}
		    <select name="department_id">
		    	{% for department in departments %}
		    		<option value="{{department.id}}">{{department.name}}</option>
		    	{% endfor %}
		    </select>
    	{% else %}
    		<select name="department_name">
    			{% for department in user.department_set.all%}
    				<option value="{{department.name}}">{{department.name}}</option>
    			{% endfor %}
    		</select>
    	{% endif %}
		<input type='submit' value='Submit'/>
	</form>
</div>
{% endblock content %}	

meeting_action_plan/action_plan/templates/add_department.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-info" align="Center"><h4>Add Department</h4></div>

<div class="add_department">
    <form method="post" action="{% url 'add_department' %}">{% csrf_token %}
    	<label for="name">Department Name:</label>
        <input id="name" type="text" name="name" value="{{name.0}}"/>
        <label>Department Head:</label>
        <select name="user_id">
        	<option value="None">None</option>
        	{% for user in users %}
        		{% if not user.is_superuser %}
        			<option value="{{user.id}}">{{user.first_name}}</option>
        		{% endif %}
        	{% endfor %}
        </select>
    	<div class="add_department_button">
            <input type='submit' value='Submit'/>
        </div>
        <p class="red_text">{{message}}</p>
        
    </form>
</div>
{% endblock %}

meeting_action_plan/action_plan/templates/add_user.html
{% extends 'base.html' %}
{% block content %}
	<body>
        <div class="alert alert-info" align="Center"><h4>Add User</h4></div>
		<form method="post" action="{% url 'add_user' %}">{% csrf_token %}
			<div class="add_user">
                <div class="user_fields">
                    <label for="username">Username:</label>
                    <input type="text"  name="username" id="username"  />
                </div>
                <div class="red_text">
                {% if message %}
                    {{message}}
                {% endif %}
                </div>
                <div class="user_fields">
                    <label for="password">Password :</label>
                    <input id="password" name="password" required="required" type="password"/>
                </div>
                <div class="user_fields">
                    <label for="firstname">First Name:</label>
                    <input type="text" name="firstname" id="firstname" />
                </div>
                <div class="user_fields">
                    <label for="lastname">Last Name:</label>
                    <input type="text" name="lastname" id="lastname" />
                </div>
                <input type='submit' value='Submit'/>
            </div>
		</form>
	</body>
{% endblock content %}	

meeting_action_plan/action_plan/templates/base.html
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
	
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="/static/css/style.css" type="text/css" />
		<link rel="stylesheet" href="/static/css/bootstrap.css" type="text/css" />
		<link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css" />
		<!-- Bootstrap -->
		<link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css" />		
		<!-- Calendar css -->
		<link rel="stylesheet" href="/static/css/calendar/datepicker_bootstrap.css">

		<script src="/static/js/lib/jquery-1.9.1.js"></script>
		
	  	<!-- Mootools -->
	  	<script src="/static/js/mootools/lib/mootools-core-1.4.5-full-compat-yc.js"></script>
		<script src="/static/js/mootools/lib/mootools-more-1.4.0.1.js"></script>
		<script src="/static/js/mootools/common.js"></script>
		
		<!-- Calendar js-->

		<script src="/static/js/mootools/calendar/Picker.js" type="text/javascript"></script>
		<script src="/static/js/mootools/calendar/Picker.Attach.js" type="text/javascript"></script>
		<script src="/static/js/mootools/calendar/Picker.Date.js" type="text/javascript"></script>
		<script src="/static/js/mootools/calendar/Picker.Date.Range.js" type="text/javascript"></script>
		{% block extraheader %}
		{% endblock extraheader %}
	</head>
	<body id="{% block body_id %}base{% endblock %}">
		<div class="container" >
			{% block header %}
				{% include 'header.html' %}
			{% endblock header %}
			<div class="content">
				{% block content %}
				{% endblock content %}
			</div>		
			<div>
			{% block footer %}
				{% include 'footer.html' %}
			{% endblock footer %}
			</div>
		</div>
	</body>
</html>

meeting_action_plan/action_plan/templates/department.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-info" align="Center"><h4>Departments</h4></div>
<div class="department">
	{% if latest_department_list %}
		<table  class="table table-striped">
			<tr >
				<th>Department</th>
				<th>Department Head</th>
				<th></th>
				<th></th>
			</tr>
			{% for department in latest_department_list %}
				<tr>
					<td>{{department.name}}</td>
					{% if department.head == None %}
						<td><a href="{% url 'editdepartment' department.id %}">Add a head</a></td>
					{% else %}
						<td>{{department.head.first_name}}</td>
					{% endif %}
					<td><a href="{% url 'editdepartment' department.id %}">Edit</a></td>
					<td><a href="{% url 'deletedepartment' department.id %}">Delete</a></td>
				</tr>
			{% endfor %}
		</table>
		
	{% else %}
			    <p>No Departments are available.</p>
	{% endif %}
	<a href="{% url 'add_department' %}">
        <input type='submit' value='Add a new Department'/>
    </a>

</div>
{% endblock content %}

meeting_action_plan/action_plan/templates/edit_action_plan.html
{% extends 'base.html' %}
{% block extraheader %}
	<script> 
		$( document ).ready(function() {
			new Picker.Date($$('#target_date'), {
	            timePicker: false,
	            positionOffset: {x: 5, y: 0},
	            pickerClass: 'datepicker_bootstrap',
	            useFadeInOut: !Browser.ie,
	            format:'%d/%m/%Y',
	        });
		});
		
	</script>
	
{% endblock extraheader %}
{% block content %}
	<body>
		{% if message %}
			<p class="red_text">{{ message }}</p>
		{% else %}
			<div class="alert alert-info" align="Center"><h4>Edit Action Plan</h4></div>

			<div class="edit_plan">
				<form method="post" action="{% url 'editactionplan' actionplan_id %}">{% csrf_token %}
					{% for field in form.visible_fields %}
						<label> {{field.label}}</label>
							{{field}}
							{{field.errors}}
					{% endfor %}
					<label> Target Date</label>
					<input id="target_date" type="text" name="target_date" value="{{target_date}}">
					<input type='submit' value='Submit'/>
				</form>
			</div>
		{% endif %}
	</body>
{% endblock content %}

meeting_action_plan/action_plan/templates/edit_department.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-info" align="Center"><h4>Edit Department</h4></div>

<div class="edit_department">
	<form method="post" action="{% url 'editdepartment' department.id %}">{% csrf_token %}
		<div class="edit_department">
			<label for="name">Department Name:</label>
			<input type="text" name="name" value="{{department.name}}" />
			<label>Department Head:</label>
			<select name="user_id" >
				<option value="None">None</option>
	        	{% for user in users %}
	        		{% if not user.is_superuser %}
	        			<option value="{{user.id}}" {% if department.head == user %}selected='true' {% endif %}>{{user.first_name}}</option>
	        		{% endif %}
	        	{% endfor %}
        	</select>

			<div class="edit_dep_button">
				<input type='submit' value='Submit'/>
				<p class="red_text">{{message}}</p>
			</div>
		</div>
	</form>
</div>
{% endblock content %}

meeting_action_plan/action_plan/templates/edit_user.html
{% extends 'base.html' %}
{% block content %}
	<body>
		<div class="alert alert-info" align="Center"><h4>Edit User</h4></div>
		<form method="post" action="{% url 'edituser' user_id %}">{% csrf_token %}
			<div class="edit_user">
				<label for="username">Username:</label>
				<input type="text" name="username" value="{{users.username}}" />
			</div class="edit_user">
			<div class="edit_user">	
				<label for="firstname">First Name:</label>
				<input type="text" name="firstname" value="{{users.first_name}}"/>
			</div>
			<div class="edit_user"> 
				<label for="lastname">Last Name:</label>
				<input type="text" name="lastname" value="{{users.last_name}}" />
			</div>
			<div class="edit_user_button">
				<input type='submit' value='Submit'/>
				<div class="red_text">{{message}}</div>
			</div>
			
		</form>
	</body>
{% endblock content %}

meeting_action_plan/action_plan/templates/header.html
<div class="header_nav">
	<div class="logo_img">
		<img src="/static/images/logo.jpg"  id="logo_image">
	<div class="logo">Meeting Action Plan</div>
	{% if user.is_authenticated %}
		

		<div class="menu">

			<li>{{user.username}}<img src="/static/images/user.png" width="24px" ></li>
			{% if user.is_superuser %}		
				<li><a href="{% url 'departments' %}">Departments </a></li>
				<li><a href="{% url 'users' %}">Users </a></li>		
			{% endif %}
			<li><a href="{% url 'actionplans' %}">Action Plan </a></li>
			<li><a href="{% url 'logout' %}">Logout </a></li>
		</div>
	{% endif %}
	</div>
</div>

meeting_action_plan/action_plan/templates/home.html
{% extends 'base.html' %}

{% block body_id %}home{% endblock %}

{% block content %}

	<div class="main_content">
		<center>
			<!-- {% if Success_message %}
                        <div>{{Success_message}}</div>
                    {% endif %} -->
			
			<h1><b>Meeting Action Plan</b></h1>
			
			
	
	    </center>
	</div>

{% endblock content %}

meeting_action_plan/action_plan/templates/login.html
{% extends 'base.html' %}

{% block body_id %}home{% endblock %}
{% block header %}
    <div class="header"></div>
{% endblock header %}
{% block content %}
    <div class="login">
                
        <form  action="{% url 'login' %}" autocomplete="on" method ="post">{% csrf_token %}
            <h1> Login</h1>
                <div class="login_sub">
                    <label for="username">Username:</label>
                            <input id="username" name="username" required="required" type="text"/>
                </div>
                        
                <div class="login_sub">
                    <label for="password">Password: </label>
                    <input id="password" name="password" required="required" type="password"style="height: auto;" />
                </div><br>
                        
                <div class="signin_button">
                    {% if message %}
                        <div>{{message}}</div>
                    {% endif %}
                    <input type="submit" value="login"/>
                </div>
                        
        </form>
    </div>
{% endblock content %}

meeting_action_plan/action_plan/templates/users.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-info" align="Center"><h4>Users</h4></div>
<div class="user">
	{% if latest_user_list %}
		<table  class="table table-striped">
			
					<tr >
						<th>User</th>
						<th>First Name</th>
						<th>Last Name</th>
						<th></th>
						<th></th>
					</tr>
					
					<tr>
						{% for user in latest_user_list %}
							{% if user.is_superuser == False %}
							<td>{{user.username}}</td>
							<td>{{user.first_name}}</td>
							<td>{{user.last_name}}</td>
							<td><a href="{% url 'edituser' user.id %}">Edit</a></td>

							<td><a href="{% url 'deleteuser' user.id %}">Delete</a></td>
					</tr>
				{% endif %}
			{% endfor %}
		</table>
	{% else %}
		<p>no users</p>
	{% endif %}
	<a href="{% url 'add_user' %}">
	    <input type='submit' value='Add a new user'/>
	</a>
</div>
{% endblock content %}